### ISSUE TITLE
Add simple priority mechanism to repo sync queue

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#190]
It would be useful to have a basic way of declaring a priority of repo sync jobs in the queue when they are _dequeued_ (i.e. certain jobs should be dequeued before others, even if they were added _after_ in time).

We should discuss, but I think a first pass would be an `int` priority column on the `repo_sync_queue` where a higher number means a higher priority.

Use case: pressing the "sync now" button should enqueue a sync with a higher priority than the "scheduled" sync jobs so that it runs "immediately" vs getting pushed to the back of the queue, if a bunch of jobs were just "scheduled"

**Comment by amenowanna** [comment]
It would be good to have default priorities set on the syncs for things like place a high priority for `GITHUB_REPO_METADATA` as we use the data in this table for things like dashboards.

**Comment by ramiroJCB** [comment]
with this change(including the migration of the column) should be enough for this  to happen 

`WITH dequeued AS (
	UPDATE mergestat.repo_sync_queue SET status = 'RUNNING'
	WHERE id IN (
		SELECT id FROM mergestat.repo_sync_queue
		WHERE status = 'QUEUED'
		ORDER BY repo_sync_queue.priority_level ASC,repo_sync_queue.created_at ASC, repo_sync_queue.id ASC LIMIT 1 FOR UPDATE SKIP LOCKED
	) RETURNING id, created_at, status, repo_sync_id
)
SELECT
	dequeued.*,
	repo_syncs.*,
	repos.repo,
	repos.ref,
	repos.is_github,
	repos.settings AS repo_settings
FROM dequeued
JOIN mergestat.repo_syncs ON mergestat.repo_syncs.id = dequeued.repo_sync_id
JOIN repos ON repos.id = mergestat.repo_syncs.repo_id
;`
but this opens up a few questions of how to handle the queue priority level  :

- should we add a  settings/column for the specific  sync to customize the priority level ? so that when we dequeue we have the ref?

- how many levels of priorities should we have ?  Critical>high>low/defualt>excluded  meaning    2>1>0>-1 ?

**Comment by amenowanna** [comment]
A numeric priority in the repo_syncs table would make sense to me. Numbers give us an unbound number of priorities so we can grow the number as needed vs a fixed set of categories. When we dequeue syncs we can order by the priority level and process those syncs first. Only concern here would be the possibility of starving lower priority syncs because of this.
