### ISSUE TITLE
Update UI for sync types

### ISSUE THREAD

**Issue by emilyvandewalle** [mergestat/fuse#194]
![https://user-images.githubusercontent.com/36261498/188908621-1da83f27-9bdf-4c5a-8664-165cd4180af3.png](https://user-images.githubusercontent.com/36261498/188908621-1da83f27-9bdf-4c5a-8664-165cd4180af3.png)

The UI for the repo sync types page should be updated:

- Currently the `status` column combines both the chart with sync running times and the enabled/disabled status (together with the grey background). We don’t want to mix these data points and look into adding a separate column
- We want to separate the scheduling versus activating of a sync type 
- We want to be more verbose/clear about what’s happening, look into renaming to `enable/disable schedule`

**Reference runscope:**
![image](https://user-images.githubusercontent.com/36261498/188911975-d0fd4571-19c0-47e4-b7ea-00ac2005bbab.png)

**Comment by patrickdevivo** [comment]
Adding the bullets from earlier today. @amenowanna @emilyvandewalle 

- [ ]  Figure out sorting of sync types (to start, maybe use the `priority`)
- [ ]  `N/A` maybe should be simplified
- [ ]  All tables should have interactive hover state
- [ ]  All table should have consistent `-` instead of `N/A`
- [ ]  `Records` should be `Log Entries`
- [ ]  Remove `...` menu in table and in upper right
- [ ]  `Learn more` should just link to docs
- [ ]  Fix extern repo url link in breadcrumb
- [ ]  Simplify sync settings to only have enabled/disabled

**Comment by patrickdevivo** [comment]
I think the last piece here is @german-mergestat we'll need to connect the schedule toggle to the graphql API to set/unset the `schedule_enabled` column.

We'll also probably want an intermediate state for that toggle while it's loading (while the request is happening).

![Image](https://user-images.githubusercontent.com/57259/195200745-a98e3c02-3abf-4b65-9228-b76e9eb3c801.png)
