### ISSUE TITLE
Review indexing on all tables

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/fuse#203]

**Comment by patrickdevivo** [comment]
IMO the main concerns here are to ensure the UI is snappy when there's a lot of repos and syncs happening. We'll want to discuss indexing on the data tables (the `public.*` schema tables) as well - these are a bit of a challenge because we don't know/want to assume what a user's query patterns are on this data. In some areas it may be obvious where we'd want an index, in others we may want to let the user manage it?

We can even discuss that being something we bring into the app management UI...(management of indexes on data tables)

Maybe we can do this together on a call @ramiroJCB @amenowanna

**Comment by amenowanna** [comment]
Resolved by #301
