### ISSUE TITLE
Add an `imported_at` (or similar) column to most/all data tables

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#66]
Often we want to know when a row was imported into a table to understand how up-to-date the data is, without looking at the sync log.

**Comment by ramiroJCB** [comment]
Do we have knowledge  of which tables   this change is not needed ?
 also now that this  is  only a migration  , we could tackle this together with https://github.com/mergestat/fuse/issues/136
@patrickdevivo  @amenowanna  what do you guys  think ?

**Comment by patrickdevivo** [comment]
Sure - so this additional column is only needed in tables on the `public` schema right now, which are our "data" tables - what users will query and what the syncs populate. The idea here is to provide some context to the data in the database so the user can see how "fresh" it is (when were rows added). It may even make sense to prefix the column names here with something like `mergestat_imported_at` or just `_imported_at`.

@amenowanna what do you think?

**Comment by patrickdevivo** [comment]
also, for the #136, I'd rather handle in two separate PRs since the functionality is quite different

**Comment by amenowanna** [comment]
@patrick and I had a quick side bar on this and landed on `_mergestat_synced_at` since we are calling the things that do the work syncs. Adding the `_mergestat` prefix makes it very clear it is internal data. Moving forward we should use this prefix. I think we will eventually need to add more columns like `_mergestat_synced_at` and `_mergestat_synced_at` but we will add those when they are needed.
